backend:
  name: git-gateway

media_folder: "site/static/img"
public_folder: "img"
publish_mode: editorial_workflow


collections:
  - name: "settings"
    label: "Settings"
    files:
      - name: "promotions"
        label: "Promotions"
        file: "site/data/promotions.yml"
        extension: "yml"
        fields:
          - label: "Promoted Items"
            name: "promoted_items"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Button Text", name: "button_text", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
              - {label: "Expiration Date", name: "expiration_date", widget: "datetime"}
      - name: "navigation"
        label: "Navigation"
        file: "site/data/navigation.yml"
        extension: "yml"
        fields:
          - label: "Primary Links"
            name: "links"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
              - label: "Mega"
                name: "mega"
                required: false
                widget: "object"
                fields:
                  - label: "Links"
                    name: "links"
                    widget: "list"
                    fields:
                      - {label: "Text", name: "text", widget: "string"}
                      - {label: "URL", name: "url", widget: "string"}
                  - label: "Featured Item"
                    name: "featured_item"
                    required: false
                    widget: "object"
                    fields:
                      - {label: "Title", name: "title", widget: "string"}
                      - {label: "Description", name: "description", widget: "string"}
                      - {label: "Image", name: "image", widget: "image"}
                      - {label: "Button Text", name: "button_text", widget: "string"}
                      - {label: "Button URL", name: "button_url", widget: "string"}
          - {name: "primary_action_text", label: "Primary Action Text", widget: "string"}
          - {name: "primary_action_url", label: "Primary Action URL", widget: "string"}
          - {name: "secondary_action_text", label: "Secondary Action Text", widget: "string"}
          - {name: "secondary_action_url", label: "Secondary Action URL", widget: "string"}
      - name: "footer"
        label: "Footer"
        file: "site/data/footer.yml"
        extension: "yml"
        fields:
          - name: "link_lists"
            label: "Link Lists"
            widget: "list"
            fields:
              - name: "title_text"
                label: "Title Text"
                widget: "string"
              - name: "title_url"
                label: "Title URL"
                required: false
                widget: "string"
              - name: "links"
                label: "Links"
                widget: "list"
                fields:
                  - name: "text"
                    label: "Text"
                    widget: "string"
                  - name: "url"
                    label: "URL"
                    widget: "string"
      - name: "employees"
        label: "Employees"
        file: "site/data/employees.yml"
        extension: "yml"
        fields:
          - name: "people"
            label: "People"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Group", name: "group", widget: "select", options: ["Leadership", "Engineering", "Business", "Product", "External Contributors"]}
              - {label: "Bio", name: "bio", widget: "text", required: false}
              - {label: "Image", name: "image", widget: "image", required: false}
              - {label: "Twitter", name: "twitter", widget: "string", required: false, hint: "username", pattern: ["^(\\w){0,15}$", "Username only (no URL, no @)"]}
              - {label: "LinkedIn", name: "linkedin", widget: "string", required: false}
      - name: "external-contributors"
        label: "External Contributors"
        file: "site/data/external-contributors.yml"
        extension: "yml"
        fields:
          - name: "people"
            label: "People"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Bio", name: "bio", widget: "text", required: false}
              - {label: "Image", name: "image", widget: "image", required: false}
              - {label: "Twitter", name: "twitter", widget: "string", required: false, hint: "username", pattern: ["^(\\w){0,15}$", "Username only (no URL, no @)"]}
              - {label: "LinkedIn", name: "linkedin", widget: "string", required: false}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Hero", name: hero, widget: object, fields: [
              {label: Title, name: title, widget: string, hint: "Use the pipe character | as a line seperator"},
              {label: Subtitle, name: subtitle, widget: markdown},
              {label: "Primary CTA", name: primary_cta, widget: object, required: false, fields: [
                {label: Text, name: text, widget: string},
                {label: URL, name: url, widget: string},
                {label: Ask for Email in Primary CTA?, name: collect_email, widget: boolean}]},
              {label: "Secondary CTA", name: secondary_cta, widget: object, required: false, fields: [
                {label: Text, name: text, widget: string},
                {label: URL, name: url, widget: string}]},
              {label: Hero Graphic, name: image, widget: image},
              {label: "Promo Slider", name: promo_slider, widget: list, fields: [
                {label: Title, name: title, widget: string, hint: "Use the pipe character | as a line seperator"},
                {label: Subtitle, name: subtitle, widget: text},
                {label: CTA Text, name: cta_text, widget: string},
                {label: CTA URL, name: cta_url, widget: string},
                {label: Graphic, name: image, widget: image}]}]}
          - {label: "Product Explainers", name: product_info, widget: list, fields: [
              {label: Icon, name: icon, widget: image},
              {label: Label, name: label, widget: string},
              {label: Title, name: title, widget: string, hint: "Use the pipe character | as a line seperator"},
              {label: Body, name: body, widget: markdown},
              {label: CTA Text, name: cta_text, widget: string},
              {label: CTA URL, name: cta_url, widget: string},
              {label: Graphic, name: image, widget: image},
              {label: Code, name: code, widget: code}]}
          - {label: "Product Differentiators", name: product_values, widget: list, fields: [
              {label: Icon, name: icon, widget: image},
              {label: Label, name: label, widget: string},
              {label: Title, name: title, widget: string, hint: "Use the pipe character | as a line seperator"},
              {label: Body, name: body, widget: markdown},
              {label: CTA Text, name: cta_text, widget: string},
              {label: CTA URL, name: cta_url, widget: string},
              {label: Graphic, name: image, widget: image},
              {label: Code, name: code, widget: code}]}
          - {label: "Input Sources", name: inputs, widget: object, fields: [
              {label: Title, name: title, widget: string, hint: "Use the pipe character | as a line seperator"},
              {label: Subtitle, name: subtitle, widget: text},
              {label: Sources, name: sources, widget: list, fields: [
                {label: Icon, name: icon, widget: image},
                {label: URL, name: url, widget: string}]},
              {label: Primary CTA Text, name: primary_cta_text, widget: string},
              {label: Primary CTA URL, name: primary_cta_url, widget: string}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Products", name: products, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Values", name: "values", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "site/content/products/_index.md"
        label: "Product"
        name: "product"
        fields:
          - {label: "Hero", name: hero, widget: object, fields: [
              {label: Title, name: title, widget: string, hint: "Use the pipe character | as a line seperator"},
              {label: Subtitle, name: subtitle, widget: text},
              {label: Primary CTA Text, name: primary_cta_text, widget: string},
              {label: Primary CTA URL, name: primary_cta_url, widget: string},
              {label: Ask for Email in Primary CTA?, name: primary_cta_email, widget: boolean},
              {label: Secondary CTA Text, name: secondary_cta_text, widget: string},
              {label: Secondary CTA URL, name: secondary_cta_url, widget: string},
              {label: Hero Graphic, name: image, widget: image},
              {label: "Promo Slider", name: promo_slider, widget: list, fields: [
                {label: Title, name: title, widget: string, hint: "Use the pipe character | as a line seperator"},
                {label: Subtitle, name: subtitle, widget: text},
                {label: CTA Text, name: cta_text, widget: string},
                {label: CTA URL, name: cta_url, widget: string},
                {label: Graphic, name: image, widget: image}]}]}
          - {label: "Product Differentiators", name: product, widget: list, fields: [
              {label: Icon, name: icon, widget: image},
              {label: Label, name: label, widget: string},
              {label: Title, name: title, widget: string, hint: "Use the pipe character | as a line seperator"},
              {label: Body, name: body, widget: markdown},
              {label: CTA Text, name: cta_text, widget: string},
              {label: CTA URL, name: cta_url, widget: string},
              {label: Graphic, name: image, widget: image},
              {label: Code, name: code, widget: code}]}
          - {label: "Input Sources", name: inputs, widget: object, fields: [
              {label: Title, name: title, widget: string, hint: "Use the pipe character | as a line seperator"},
              {label: Subtitle, name: subtitle, widget: text},
              {label: Sources, name: sources, widget: list, fields: [
                {label: Icon, name: icon, widget: image},
                {label: URL, name: url, widget: string}]},
              {label: Primary CTA Text, name: primary_cta_text, widget: string},
              {label: Primary CTA URL, name: primary_cta_url, widget: string}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Products", name: products, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Values", name: "values", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
  - name: "blog"
    label: "Blog"
    folder: "site/content/blog"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        pattern: ["^.{3,65}$", "Title must be between 3 and 65 characters"]
      - label: Category
        name: category
        widget: select
        options: ["Company News", "Product Developments", "Technical Writing", "Opinion"]
      - label: "Authors"
        name: "authors"
        widget: "relation"
        collection: "settings"
        file: "employees"
        search_fields: ["people.*.name"]
        value_field: "people.*.name"
        multiple: true
      - label: "External Contributors"
        name: "external_contributors"
        widget: "relation"
        collection: "settings"
        file: "external-contributors"
        search_fields: ["people.*.name"]
        value_field: "people.*.name"
        multiple: true
        required: false
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Short Description"
        name: "description"
        widget: "text"
        hint: "Short, text-only description shown in index pages and search results, no more than 155 chars"
        pattern: ["^.{40,155}$", "Description must be between 40 and 155 characters"]
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Header Image"
        name: "image"
        widget: "image"
        required: false
      - label: "Browser Title"
        name: "browser_title"
        hint: "Override post title in browser <title> tag with this field."
        widget: "string"
        required: false
        pattern: ["^.{,65}$", "Must be no more than 65 characters"]
  - name: "events"
    label: "Events"
    folder: "site/content/events"
    hint: "Any kind of date-specific event, e.g. community meetups, webinars, conferences, podcasts, etc..."
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        pattern: ["^.{3,65}$", "Title must be between 3 and 65 characters"]
      - label: Category
        name: category
        widget: select
        options: ["Community Meetup", "Conference", "Podcast", "Product Demo"]
      - label: "Participants"
        name: "participants"
        widget: "relation"
        collection: "settings"
        file: "people"
        search_fields: ["people.*.name"]
        value_field: "people.*.name"
        multiple: true
      - label: "Event Date"
        name: "datetime"
        widget: "datetime"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Header Image"
        name: "image"
        widget: "image"
        required: false
      - label: "Browser Title"
        name: "browser_title"
        widget: "string"
        required: false
  - name: "case-studies"
    label: "Case Studies"
    hint: "Reports on how customers are using Materialize."
    folder: "site/content/case-studies"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - label: Category
        name: category
        widget: select
        options: ["Case Study", "Company", "Databases", "Deep-dive", "Ecosystem", "Events", "News", "Product", "Release", "Research", "Rust", "Streaming", "Timely", "Uncategorized", "Use Case"]
      - label: "Authors"
        name: "authors"
        widget: "relation"
        collection: "settings"
        file: "employees"
        search_fields: ["people.*.name"]
        value_field: "people.*.name"
        multiple: true
      - label: "External Contributors"
        name: "external_contributors"
        widget: "relation"
        collection: "settings"
        file: "external-contributors"
        search_fields: ["people.*.name"]
        value_field: "people.*.name"
        multiple: true
        required: false
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - label: "Short Description"
        name: "description"
        widget: "text"
        hint: "Succinct, text-only description shown in index pages and search results, no more than 155 chars"
        pattern: ["^.{40,155}$", "Description must be between 40 and 155 characters"]
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Header Image", name: "image", widget: "image", required: false}
      - {label: "Browser Title", name: "browser_title", widget: "string", required: false}
  - name: "reports"
    label: "Reports"
    hint: "Reports are more in-depth pieces of content, usually gated behind an email request form."
    folder: "site/content/reports"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: Category
        name: category
        widget: select
        options: ["Benchmark", "Business Research", "Technical Research", "Competitive Research"]
      - label: "Authors"
        name: "authors"
        widget: "relation"
        collection: "settings"
        file: "employees"
        search_fields: ["people.*.name"]
        value_field: "people.*.name"
        multiple: true
      - label: "External Contributors"
        name: "external_contributors"
        widget: "relation"
        collection: "settings"
        file: "external-contributors"
        search_fields: ["people.*.name"]
        value_field: "people.*.name"
        multiple: true
        required: false
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Short Description"
        name: "description"
        widget: "text"
        hint: "Succinct, text-only description shown in index pages and search results, no more than 155 chars"
        pattern: ["^.{40,155}$", "Description must be between 40 and 155 characters"]
      - label: "Ungated Body"
        name: "ungated_body"
        widget: "markdown"
        hint: "Rich-text or markdown formatted body content to be shown publicly."
      - label: "Gated Body"
        name: "gated_body"
        widget: "markdown"
        hint: "If used, a form will be displayed, asking the user to submit email to get access."
        required: false
      - label: "Gated File"
        name: "gated_file"
        widget: "file"
        hint: "If specificed, a form will be displayed asking the user to submit email to download."
        required: false
      - label: "Header Image"
        name: "image"
        widget: "image"
        required: false
      - label: "Browser Title"
        name: "browser_title"
        widget: "string"
        required: false